import type {
  Comparison,
  Conversation,
  Dialect,
  Prefecture,
  Quiz,
  Region,
} from "./domain";
const areas: Record<string, string[]> = {
  北海道: ["北海道"],
  東北: ["青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県"],
  関東: [
    "茨城県",
    "栃木県",
    "群馬県",
    "埼玉県",
    "千葉県",
    "東京都",
    "神奈川県",
  ],
  中部: [
    "新潟県",
    "富山県",
    "石川県",
    "福井県",
    "山梨県",
    "長野県",
    "岐阜県",
    "静岡県",
    "愛知県",
  ],
  近畿: [
    "三重県",
    "滋賀県",
    "京都府",
    "大阪府",
    "兵庫県",
    "奈良県",
    "和歌山県",
  ],
  中国: ["鳥取県", "島根県", "岡山県", "広島県", "山口県"],
  四国: ["徳島県", "香川県", "愛媛県", "高知県"],
  "九州・沖縄": [
    "福岡県",
    "佐賀県",
    "長崎県",
    "熊本県",
    "大分県",
    "宮崎県",
    "鹿児島県",
    "沖縄県",
  ],
};
const names = Object.values(areas).flat();
export const prefectures: Prefecture[] = names.map((name, i) => ({
  id: `p${i + 1}`,
  code: i + 1,
  name,
  area: Object.entries(areas).find(([, v]) => v.includes(name))?.[0] ?? "",
  summary: `${name}の地域ごとに受け継がれる、暮らしのことばをたどります。`,
  active: ["福岡県", "大阪府", "青森県"].includes(name),
}));
const pid = (name: string) => prefectures.find((p) => p.name === name)!.id;
export const regions: Region[] = [
  ["福岡県", "福岡市周辺", "人の行き来とともに多様な言い方が交わる地域。"],
  ["福岡県", "北九州", "港町の歴史を背景にしたことばが残ります。"],
  ["福岡県", "筑後", "筑後平野の暮らしに根ざした表現。"],
  ["大阪府", "大阪市", "商いと笑いの文化が息づくことば。"],
  ["大阪府", "河内", "勢いと親しみのある語り口が特徴的。"],
  ["大阪府", "泉州", "祭りと暮らしの中で育ったことば。"],
  ["青森県", "津軽", "雪国の暮らしと濃やかな感情を伝えることば。"],
  ["青森県", "南部", "岩手県境にもつながる穏やかなことば。"],
  ["青森県", "下北", "半島の風土を映す独自の言い回し。"],
].map((r, i) => ({
  id: `r${i + 1}`,
  prefectureId: pid(r[0]),
  name: r[1],
  description: r[2],
}));
const rid = (name: string) => regions.find((r) => r.name === name)!.id;
const base = (
  id: string,
  phrase: string,
  reading: string,
  std: string,
  desc: string,
  example: string,
  exampleStd: string,
  pref: string,
  region: string,
  ages: string[],
  contexts: string[],
  emotions: string[],
  freq: Dialect["usageFrequency"],
): Dialect => ({
  id,
  phrase,
  reading,
  standardJapanese: std,
  description: desc,
  exampleDialect: example,
  exampleStandard: exampleStd,
  prefectureId: pid(pref),
  regionId: rid(region),
  ageGroups: ages,
  usageContexts: contexts,
  emotionTags: emotions,
  usageFrequency: freq,
  recordingYear: 2024,
  verificationStatus: "demo",
  sourceType: "demo",
  createdAt: "2024-06-01",
  updatedAt: "2026-08-01",
  reactions: { use: 0, heard: 0, new: 0 },
});
export const dialects: Dialect[] = [
  base(
    "d1",
    "なんしようと？",
    "なんしようと",
    "何をしているの？",
    "相手の様子をたずねる、親しい響きの表現。",
    "今、なんしようと？",
    "今、何をしているの？",
    "福岡県",
    "福岡市周辺",
    ["10〜30代", "40〜60代"],
    ["日常会話"],
    ["親しみ", "問いかけ"],
    "よく使う",
  ),
  base(
    "d2",
    "ばり",
    "ばり",
    "とても",
    "程度が大きいことを表す言い方。",
    "これ、ばりうまい！",
    "これ、とてもおいしい！",
    "福岡県",
    "福岡市周辺",
    ["10〜30代"],
    ["食事", "日常会話"],
    ["驚き", "喜び"],
    "よく使う",
  ),
  base(
    "d3",
    "なおす",
    "なおす",
    "片づける",
    "物を元の場所へしまう意味で使う例。",
    "その本、なおしといて。",
    "その本、片づけておいて。",
    "大阪府",
    "大阪市",
    ["全年代"],
    ["家庭", "日常会話"],
    ["お願い"],
    "よく使う",
  ),
  base(
    "d4",
    "ほんま？",
    "ほんま",
    "本当？",
    "驚きや確認をやわらかく伝える表現。",
    "ほんま？ 知らんかったわ。",
    "本当？ 知らなかった。",
    "大阪府",
    "河内",
    ["全年代"],
    ["日常会話"],
    ["驚き", "問いかけ"],
    "よく使う",
  ),
  base(
    "d5",
    "めんこい",
    "めんこい",
    "かわいい",
    "人や動物を愛らしく思う気持ちを表す言葉。",
    "この子、めんこいなあ。",
    "この子、かわいいね。",
    "青森県",
    "津軽",
    ["40〜60代", "70代以上"],
    ["家庭", "ほめる"],
    ["愛情"],
    "ときどき",
  ),
  base(
    "d6",
    "けっぱる",
    "けっぱる",
    "がんばる",
    "励ましや意気込みに使われる表現。",
    "もう少し、けっぱれ！",
    "もう少し、がんばれ！",
    "青森県",
    "津軽",
    ["全年代"],
    ["応援"],
    ["励まし"],
    "ときどき",
  ),
  base(
    "d7",
    "だべ",
    "だべ",
    "でしょう",
    "同意を求めたり推量したりするときの語尾。",
    "今日は寒いべ。",
    "今日は寒いでしょう。",
    "青森県",
    "南部",
    ["全年代"],
    ["日常会話"],
    ["共感"],
    "よく使う",
  ),
  base(
    "d8",
    "せからしか",
    "せからしか",
    "うるさい・わずらわしい",
    "状況により強さが変わるため、関係性に配慮したい表現。",
    "蝉がせからしかね。",
    "蝉がうるさいね。",
    "福岡県",
    "筑後",
    ["40〜60代", "70代以上"],
    ["日常会話"],
    ["困惑"],
    "懐かしい",
  ),
];
export const conversations: Conversation[] = [
  {
    id: "c1",
    title: "帰り道、夕飯の相談",
    description: "気心の知れた二人が、帰り道に話す短い会話です。",
    prefectureId: pid("福岡県"),
    regionId: rid("福岡市周辺"),
    usageContext: "友人との日常",
    speakers: [
      { name: "ミナ", ageGroup: "20代", origin: "福岡市周辺" },
      { name: "ユウ", ageGroup: "20代", origin: "北九州" },
    ],
    lines: [
      {
        speaker: "ミナ",
        dialectText: "今なんしようと？",
        standardText: "今何してるの？",
        dialectId: "d1",
      },
      {
        speaker: "ユウ",
        dialectText: "帰りよる。なんか食べる？",
        standardText: "帰っているところ。何か食べる？",
      },
      {
        speaker: "ミナ",
        dialectText: "あの店、ばり気になっとった。",
        standardText: "あのお店、とても気になっていた。",
        dialectId: "d2",
      },
    ],
    recordedYear: 2024,
    verificationStatus: "demo",
  },
  {
    id: "c2",
    title: "写真を見ながら",
    description: "家族で昔の写真を眺める場面。",
    prefectureId: pid("青森県"),
    regionId: rid("津軽"),
    usageContext: "家族の会話",
    speakers: [
      { name: "祖母", ageGroup: "70代", origin: "津軽" },
      { name: "孫", ageGroup: "10代", origin: "津軽" },
    ],
    lines: [
      {
        speaker: "祖母",
        dialectText: "おめ、小さいころからめんこいな。",
        standardText: "あなた、小さいころからかわいいね。",
        dialectId: "d5",
      },
      {
        speaker: "孫",
        dialectText: "ほんと？ この写真はずかしい。",
        standardText: "本当？ この写真、恥ずかしい。",
      },
    ],
    recordedYear: 2024,
    verificationStatus: "demo",
  },
];
export const comparisons: Comparison[] = [
  "何してるの？",
  "本当？",
  "疲れた",
  "早く帰ろう",
  "おいしい",
].map((prompt, i) => ({
  id: `x${i}`,
  prompt,
  entries: [
    {
      prefectureId: pid("福岡県"),
      phrase: [
        "なんしようと？",
        "ほんと？",
        "きつかー",
        "はよ帰ろう",
        "うまか",
      ][i],
    },
    {
      prefectureId: pid("大阪府"),
      phrase: [
        "何してんの？",
        "ほんま？",
        "しんどい",
        "はよ帰ろ",
        "めっちゃうまい",
      ][i],
    },
    {
      prefectureId: pid("青森県"),
      phrase: ["何してら？", "ほんとだが？", "こえじゃ", "早ぐ帰るべ", "めぇ"][
        i
      ],
    },
  ],
}));
export const quizzes: Quiz[] = Array.from({ length: 10 }, (_, i) => {
  const d = dialects[i % dialects.length];
  return {
    id: `q${i}`,
    question:
      i % 2
        ? `「${d.phrase}」に近い意味は？`
        : `「${d.phrase}」の使用例がある県は？`,
    choices:
      i % 2
        ? [d.standardJapanese, "おはよう", "また明日", "ゆっくり"]
        : [
            prefectures.find((p) => p.id === d.prefectureId)!.name,
            "東京都",
            "沖縄県",
            "北海道",
          ],
    answer: 0,
    explanation: `${prefectures.find((p) => p.id === d.prefectureId)!.name}${regions.find((r) => r.id === d.regionId)!.name}での使用例として紹介しています。`,
    dialectId: d.id,
    difficulty: i < 3 ? "やさしい" : i < 8 ? "ふつう" : "むずかしい",
  };
});
